
server:
  port: 9393

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs


user:
  service:
    host: ${USER_SERVICE_HOST:my-spring-boot-app}
    port: ${USER_SERVICE_PORT:9090}
    path: ${USER_SERVICE_PATH:/user}